name: Publish to NPM

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          cache: yarn
      - run: yarn install
      - run: yarn playwright install
      - run: yarn build
      - run: yarn test
      - name: Read version and publish
        run: npm publish --access public
